[package]
name = "craindown"
version = "0.1.0"
authors = ["J. Andrew Crain <andrew@crain.family>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
